### DISCUSSION TITLE
How to load environment from `.env` files

### DISCUSSION THREAD

**Discussion by DenuxPlays** [loco-rs/loco#1022] [General]
**Description**

I've set up my development.yaml file to load env vars but it seems that the whole parsing process does not load a .env file before parsing the config.

**To Reproduce**

Add this to your config:
```yaml
# Queue Configuration
queue:
  kind: Redis
  # Redis connection URI
  uri: {{get_env(name="REDIS_URL")}}
  # Dangerously flush all data in Redis on startup. dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_flush: false
  ```
Now execute:
```
cargo loco db create
```

See a parsing error.

**Expected Behavior**

Load the env vars from the `.env` file.

**Environment:**

**Additional Context**

/
