### DISCUSSION TITLE
Multipart form size limit clarification

### DISCUSSION THREAD

**Discussion by BWStearns** [loco-rs/loco#1069] [Q&A]
I ran into an issue with file uploading. It appears that I can upload small files, but not those above 2MB, despite `limit_payload` being disabled. Is there another setting that also controls this? (`cargo loco middleware --config` output below)

```
cors                   {"allow_headers":["*"],"allow_methods":["*"],"allow_origins":["any"],"enable":true,"max_age":null,"vary":["origin","access-control-request-method","access-control-request-headers"]}
catch_panic            {"enable":true}
etag                   {"enable":true}
static                 {"enable":true,"fallback":"frontend/dist/index.html","folder":{"path":"frontend/dist","uri":"/"},"must_exist":true,"precompressed":false}
logger                 {"config":{"enable":true},"environment":"development"}
request_id             {"enable":true}
fallback               {"code":200,"enable":true,"file":null,"not_found":null}
powered_by             {"ident":"loco.rs"}


limit_payload          (disabled)
remote_ip              (disabled)
compression            (disabled)
timeout_request        (disabled)
secure_headers         (disabled)
```

**Comment by BWStearns** [comment]
I found _a_ fix for my particular problem. It appears that `limit_payload: enable: false` doesn't actually disable the payload limit. So you can either set one in the configs sufficiently high for your work, or you can add a specific limit on a specific route to override it there. Is the intent for `enable: false` to remove the limit?

```yaml
# development.yaml
server:
  # ... other settings
  middlewares:
    # Limit payload size for incoming requests.
    limit_payload:
      enable: true
      # Maximum payload size in bytes.
      body_limit: 10485760 # 1MB
```

```rust
# src/controllers/foo.rs

const MAX_FILE_SIZE: usize = 1024 * 1024 * 10; // 10MB

Routes::new()
    .prefix("api/foo")
    .add("/", post(upload)).layer(DefaultBodyLimit::max(MAX_FILE_SIZE))
```
