### DISCUSSION TITLE
How to make the server return 404 for unhandled route?

### DISCUSSION THREAD

**Discussion by cpunion** [loco-rs/loco#1103] [General]
I'm using loco 0.13.2, currently it always returns 200 even the route not exists. Seems https://github.com/loco-rs/loco/pull/991 make this, what the right way to return 404 for an unhandled route?

I just tried to enable `fallback` middleware, it's not effected.

My development.yml:

```yaml
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: 5150
  # The UI hostname or IP address that mailers will point to.
  host: http://localhost
  # Out of the box middleware configuration. to disable middleware you can changed the `enable` field to `false` of comment the middleware block
  middlewares:
    fallback:
      enable: true
      code: 404
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/"
        path: "frontend/dist"
      fallback: "frontend/dist/index.html"
```
