### DISCUSSION TITLE
Logs from request/controller tests.

### DISCUSSION THREAD

**Discussion by felipesere** [loco-rs/loco#1179] [Q&A] [answered]
I have test failing with a 500, but I can't tell where it's really happening as I see no logs from the app.
This is my `test.yaml`:
```yaml
logger:
  # Enable or disable logging.
  enable: true
  # Log level, options: trace, debug, info, warn or error.
  level: trace
  # Define the logging format. options: compact, pretty or Json
  format: compact
  # By default the logger has filtering only logs that came from your code or logs that came from `loco` framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  override_filter: trace
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: 5150
  # The UI hostname or IP address that mailers will point to.
  host: http://localhost
  # Out of the box middleware configuration. to disable middleware you can changed the `enable` field to `false` of comment the middleware block
  middlewares:
    # Allows to limit the payload size request. payload that bigger than this file will blocked the request.
    limit_payload:
      # Enable/Disable the middleware.
      enable: true
      # the limit size. can be b,kb,kib,mb,mib,gb,gib
      body_limit: 5mb
    # Generating a unique request ID and enhancing logging with additional information such as the start and completion of request processing, latency, status code, and other request details.
    logger:
      # Enable/Disable the middleware.
      enable: true
    # when your code is panicked, the request still returns 500 status code.
    catch_panic:
      # Enable/Disable the middleware.
      enable: false
```

All I see from the test failure is

```
running 1 test
test requests::recipes::can_create_and_update_a_recipe ... FAILED

failures:

---- requests::recipes::can_create_and_update_a_recipe stdout ----
[tests/requests/recipes.rs:68:9] &t = "{\"error\":\"internal_server_error\",\"description\":\"Internal Server Error\"}"
thread 'requests::recipes::can_create_and_update_a_recipe' panicked at tests/requests/recipes.rs:69:9:
assertion `left == right` failed
  left: 500
 right: 200
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'd hope to see a few my `tracing::info!("something here...!")` within my app.

Am I missing something? 😅
