### DISCUSSION TITLE
"Invalid CORS configuration" error

### DISCUSSION THREAD

**Discussion by alokmahor** [loco-rs/loco#1300] [Q&A]
I have added CORS config in `config/development.yaml` as 
```yaml
middlewares:
    cors:
      enable: true
      allow_origin: "http://localhost:5173" # You can replace "*" with "http://localhost:5173" for better security
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Authorization", "Content-Type"]
      allow_credentials: true
```
This Configuration gives me error 

```
thread 'main' panicked at /Users/alok/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/tower-http-0.6.2/src/cors/mod.rs:798:9:
Invalid CORS configuration: Cannot combine `Access-Control-Allow-Credentials: true` with `Access-Control-Allow-Origin: *`
```
What is wrong in my Configuration?
