### DISCUSSION TITLE
How to use a specific queue name for a background worker?

### DISCUSSION THREAD

**Discussion by oco-adam** [loco-rs/loco#1306] [Q&A] [answered]
Hi, I'm trying to use a specific (custom) queue name for a background worker. It looks like I should be able to set this in the worker as follows:

```rust
#[async_trait]
impl BackgroundWorker<MyWorkerArgs>
    for MyWorker
{
    fn build(ctx: &AppContext) -> Self {
        Self { ctx: ctx.clone() }
    }
    fn queue() -> Option<String> {
        Some("myqueue".to_string())
    }
    ...
```
I have the following in my `development.yaml`:

```yaml
# Worker Configuration
workers:
  mode: BackgroundQueue

# Queue Configuration
queue:
  kind: Redis
  uri: {{ get_env(name="REDIS_URL", default="redis://127.0.0.1:6379") }}
  dangerously_flush: false

```

I'm trying to get this to work locally as follows:

Starting two processes in two different terminal windows by running `cargo loco start` in one and `cargo loco start --worker` in the other.

When I submit a job, I can see the job go into the Redis list "queue:myqueue" however the job never seems to be picked up by a worker.

The worker picks it up and runs fine if I remove the  `fn queue() -> Option<String>`  implementation from the `BackgroundWorker` trait implementation, or if I eg use Postgres as the queue provider or a different worker mode.

When my worker process starts locally it looks like this:

```bash
cargo loco start --worker
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.19s
     Running `target/debug/brandi-cli start --worker`
2025-03-18T13:09:44.450740Z  WARN app: loco_rs::boot: pretty backtraces are enabled (this is great for development but has a runtime cost for production. disable with `logger.pretty_backtrace` in your config yaml) environment=development
2025-03-18T13:09:44.460030Z DEBUG app: loco_rs::bgworker: workers setup environment=development
2025-03-18T13:09:44.514260Z DEBUG app: loco_rs::bgworker: register worker worker="MailerWorker" environment=development
2025-03-18T13:09:44.514348Z DEBUG app: loco_rs::bgworker: register worker worker="MyWorker" environment=development
2025-03-18T13:09:44.514556Z DEBUG app: loco_rs::boot: done registering workers and queues environment=development

                      ▄     ▀                     
                                 ▀  ▄             
                  ▄       ▀     ▄  ▄ ▄▀           
                                    ▄ ▀▄▄         
                        ▄     ▀    ▀  ▀▄▀█▄       
                                          ▀█▄     
▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄ ▄▄▄▄▄▄▄▄▄ ▀▀█    
 ██████  █████   ███ █████   ███ █████   ███ ▀█   
 ██████  █████   ███ █████   ▀▀▀ █████   ███ ▄█▄  
 ██████  █████   ███ █████       █████   ███ ████▄
 ██████  █████   ███ █████   ▄▄▄ █████   ███ █████
 ██████  █████   ███  ████   ███ █████   ███ ████▀
   ▀▀▀██▄ ▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀ ██▀  
       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    
                https://loco.rs

environment: development
     logger: debug
compilation: debug
      modes: worker

worker is online
2025-03-18T13:09:44.514657Z DEBUG app: loco_rs::boot: note: worker is run in-process (tokio spawn) environment=development
2025-03-18T13:09:44.514702Z DEBUG loco_rs::bgworker: running background jobs
```

Any help with this would be greatly appreciated.

**Comment by oco-adam** [comment, marked as answer]
Ok so I looked a bit more into the implementation of the background workers and I just needed to add the custom queues to the config yaml i.e.:

```
# Worker Configuration
workers:
  mode: BackgroundQueue

# Queue Configuration
queue:
  kind: Redis
  uri: {{ get_env(name="REDIS_URL", default="redis://127.0.0.1:6379") }}
  dangerously_flush: false
  queues: ["myqueue"]
  ```
