### DISCUSSION TITLE
Scheduler inilization failed

### DISCUSSION THREAD

**Discussion by thaarrtt** [loco-rs/loco#1465] [Q&A] [answered]
can someone give an example of scheduler file in yaml please???
mine is like this

`
jobs:
  - name: process_pending_payments
    schedule: "*/5 * * * *" # Every 5 minutes
    run: "enqueue_pending_payments"
    run_on_start: true
  - name: scheduled_greeting
    schedule: "*/1 * * * *" # Every minute
    run: "greeting_task"    
    run_on_start: false   
`

**Comment by thaarrtt** [comment]


**Reply by kaplanelad** [reply]
Hey @thaarrtt, did you follow the documentation here?
https://loco.rs/docs/processing/scheduler/#2-environment-configuration-file

**Reply by thaarrtt** [reply]
like this??

![image](https://github.com/user-attachments/assets/584cfee6-81c9-4864-8a19-5046b32393b8)

thing is not running

**Reply by kaplanelad** [reply]
how do you running the server?

**Reply by thaarrtt** [reply]
> how do you running the server?

already server and worker mode

CMD ["/usr/app/thesa-cli", "start", "-s"]

**Reply by kaplanelad** [reply]
The scheduler process will not run by default. You have two options:

1. Run it as part of the main server process using the `--all` flag (note that it will also run the worker process).
2. Run the scheduler as a separate process using:
   `cargo loco scheduler`

**Reply by thaarrtt** [reply]
> The scheduler process will not run by default. You have two options:
> 
> 1. Run it as part of the main server process using the `--all` flag (note that it will also run the worker process).
> 2. Run the scheduler as a separate process using:
>    `cargo loco scheduler`

oh its new tag, thank god

last time I check there is no -a tag

**Comment by thaarrtt** [comment]
I facking hate yaml

**Reply by kaplanelad** [reply]
this is not related yaml

**Reply by thaarrtt** [reply]
> this is not related yaml

I know its yaml fault

Error: Scheduler(Empty)

how can it empty

**Comment by thaarrtt** [comment]
@kaplanelad can you just give me your scheduler.yaml file please

I can just edit and start from there

**Reply by kaplanelad** [reply]
i tested it by copy the config from the docs. 
where did you put the configuration? in a dedicated file? or under env yaml?

**Reply by thaarrtt** [reply]
> i tested it by copy the config from the docs. where did you put the configuration? in a dedicated file? or under env yaml?

dedicated under scheduler.yaml

**Comment by kaplanelad** [comment]
if you using with cargo loco start --all
the configuration should be under the env yaml file

**Reply by thaarrtt** [reply]
> if you using with cargo loco start --all the configuration should be under the env yaml file

so what should I do for dedicated file ?

**Reply by kaplanelad** [reply, marked as answer]
Use an env var like the following:
```
SCHEDULER_CONFIG=config/scheduler.yaml cargo loco start --all
```

and see the scheduler.yaml content
```
❯ cat config/scheduler.yaml
  # Location of shipping the command stdout and stderr.
  output: stdout
  # A list of jobs to be scheduled.
  jobs:
    # The name of the job.
    write_content:
      # by default false meaning executing the the run value as a task. if true execute the run value as shell command
      shell: true
      # command to run
      run: "echo loco >> ./scheduler.txt"
      # The cron expression that defines the job's schedule.
      schedule: run every 1 second
      output: silent
      tags: ['base', 'infra']

    run_task:
      run: "foo"
      schedule: "at 10:00 am"
      run_on_start: true

    list_if_users:
      run: "user_report"
      shell: true
      schedule: "* 2 * * * *"
      tags: ['base', 'users']⏎
```
