### DISCUSSION TITLE
How I deployed Loco using Docker on a Plesk server

### DISCUSSION THREAD

**Discussion by LimpidCrypto** [loco-rs/loco#279] [Show and tell]
## Disclaimer
This is just meant to give you a general overview on how i managed to deploy my loco app. Do not take this as a good practice I'm actually curious about what I could do better :)

[Post about how to deploy](https://loco.rs/docs/getting-started/deployment/)

## Overview
- Disable nginx proxy mode (using Plesk)
- Add `docker-compose.yml` to your loco project
- Add `Dockerfile` to your loco project
- Add `.dockerignore` to your loco project
- Add `.env` to your loco project

## Disable nginx proxy mode (using Plesk)
- Navigate to "Websites & Domains"
- Click on the Domain you want to use to access your loco app
- Navigate to "Hosting & DNS"
- Click "Apache & Nginx"
- Remove the tick "Proxy mode" for "nginx settings"
- In the section "Additional nginx directives" add the following:
```
location / {
	proxy_pass http://localhost:3000;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
}
```
**This config assumes your loco app is running on localhost:3000**
- Apply the changes

## Add `docker-compose.yml` to your loco project
```yml
version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    networks:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/workspaces:cached
    env_file:
      - .env
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - redis

volumes:
  postgres-data:


networks:
  db:
  redis:
```
## Add `Dockerfile` to your loco project
```
FROM node:latest as npm-builder

WORKDIR /usr/src/frontend/

COPY ./frontend/ ./

RUN npm install -g @angular/cli && npm install && npm run build

FROM rust:1.74-slim as rust-builder

WORKDIR /usr/src/backend/

COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

WORKDIR /usr/app

COPY --from=npm-builder /usr/src/frontend/dist/frontend/browser /usr/app/frontend/dist/frontend/browser
COPY --from=npm-builder /usr/src/frontend/dist/frontend/browser/index.html /usr/app/frontend/dist/frontend/browser/index.html
COPY --from=rust-builder /usr/src/backend/config /usr/app/config
COPY --from=rust-builder /usr/src/backend/target/release/website-cli /usr/app/website-cli

EXPOSE 3000

CMD ["/usr/app/website-cli", "start", "-e", "production"]
```
## Add `.dockerignore` to your loco project
```
target
dockerfile
.dockerignore
.git
.gitignore
```
## Add `.env` to your loco project
```
POSTGRES_DB=loco_app
POSTGRES_USER=loco
POSTGRES_PASSWORD=loco
DATABASE_URL=postgres://loco:loco@db:5432/loco_app
REDIS_URL=redis://redis:6379
```

This deployment assumes you have your whole project on your server, not only the build.
