### DISCUSSION TITLE
localhost email test doesn't work with `REST API` starter

### DISCUSSION THREAD

**Discussion by AkifumiSato** [loco-rs/loco#448] [Q&A]
I sent a request to `/api/auth/forgot` with `REST API` starter, but could not confirm the transmission at `http://localhost:1080/`.
The localhost stmp server is configured with docker-compose as follows.

```yml
services:
  # ...
  mailer:
    image: mailtutan/mailtutan:latest
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1025:1025
```

I could see the UI on localhost:1080, so maybe it's not being sent to the stmp server, I couldn't figure out the cause of the problem myself.
Can you help me?
