### DISCUSSION TITLE
How can I use loco-rs with workspace resolver=2?

### DISCUSSION THREAD

**Discussion by aitiotekt** [loco-rs/loco#460] [Q&A]
I have a cargo workspace with `resolver = "2"` and loco-rs projects in `<workspace-root>/crates/loco-appn`, but it seems can not support the kind of project structure now, for examples:

- configs must be placed at `<workspace-root>/config/<environment.yaml>`, so have to set environment like `loco-appn.development`
- have to edit alias to `run -p loco-appn --bin loco-appn-cli -- --environment loco-appn.development` to enable `cargo loco-appn start`, but still not support `loco generate` etc, as files will be generated to `<workspace-root>/src/xxx`

Is there any plan to support cargo workspace?

**Comment by jondot** [comment]
can you please create a sample project that reproduces the issue and put it somewhere on github? 
if we have a repo that reproduces the issue we can even start working on a solution

**Reply by aitiotekt** [reply]
Thanks to your reply, I reproduced a simplified demo project
https://github.com/lonelyhentxi/loco-rs-workspace-issue-demo

It has two loco-rs apps, `loco_app1` and `loco_app2`, and a shared library `share_lib`.

The following alias is used for quick start:

```toml
[alias]
loco-app1 = "run -p loco_app1 --bin loco_app1_cli -- --environment loco_app1.development"
loco-app1-playground = "run -p loco_app1 --example playground -- --environment loco_app1.development"
loco-app2 = "run -p loco_app2 --bin loco_app2_cli -- --environment loco_app2.development"
loco-app2-playground = "run -p loco_app2 --example playground -- --environment loco_app2.development"
```

So you can use the following command to start:

```shell
# or other loco-rs cli command
cargo loco-app1 start
```

However, the problem is that the current commands seem to be relative to `<workspace-root>`, not `<project-root>`. This makes things like `include_dir` of `mailers` need to be edit and makes reading env config and generating files difficult or impossible to use, and must be adjusted manually.
