### DISCUSSION TITLE
Sendgrid integration not working like in example?

### DISCUSSION THREAD

**Discussion by BWStearns** [loco-rs/loco#597] [General]
I'm trying to get my auth email/verification workflow working but running into a kind of silent failure.

This is my relevant Mailer config in `development.yaml` but when I sign up a user on local (using `cargo-watch -x check  -s 'cargo loco start --server-and-worker'` to start my server) I don't get any error but I also never send an email. Is there some setup/config step that I'm missing? I notice that we don't explicitly start the mailer worker in App.rs. Does the MailerWorker not automatically get started with Loco?

```
# Mailer Configuration.
mailer:
  # SMTP mailer configuration.
  smtp:
    # Enable/Disable smtp mailer.
    enable: true
    # SMTP server host. e.x localhost, smtp.gmail.com {{ get_env(name="MAILER_HOST", default="localhost") }}
    host: "smtp.sendgrid.net"
    # SMTP server port
    port: 465
    # Use secure connection (SSL/TLS).
    secure: true
    auth:
      user: "apikey"
      password: "SG.123ABCDEF-jkLoLWtf.mySuperSecretKeyIsHere"
```

Update:

I've switched to using `BackgroundQueue` locally and confirmed that the AuthMailer does put an email on the queue to send.

<img width="595" alt="image" src="https://github.com/loco-rs/loco/assets/3485638/a4c14efa-d56f-4711-ac14-e04bd54e3af8">

When I start up a worker with `cargo loco start --worker` the worker consumes the items in `queue:mailer` but it doesn't emit any errors and no emails get sent. Is there any way to make the mailer worker more verbose or is there something obviously wrong with my mailer config?
