### DISCUSSION TITLE
Allow placeholder values in configuration files

### DISCUSSION THREAD

**Discussion by FaveroFerreira** [loco-rs/loco#80] [Ideas]
I took a look at the source code, and looks like `loco` expects us override configurations defined in the `config-{env}.yaml` with environment variables with an specific `APP__` prefix.

Sometimes we do not decide how our environment variables will be named, so we don't get to define them with prefixes like `APP__`

It would be nice if we could declare placeholders in our configuration files where the values should be taken from our environment variables.

Example:

```yaml
database:
  uri: ${DB_URI:postgres://loco:loco@localhost:5432/loco_app} #value taken from the DB_URI or uses the default value after ':' 
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 1
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false
```
