### ISSUE TITLE
Loco .yaml configuration files does not load .env files

### ISSUE THREAD

**Issue by DenuxPlays** [loco-rs/loco#1020]
**Description**

I've set up my development.yaml file to load env vars but it seems that the whole parsing process does not load a .env file before parsing the config.

**To Reproduce**

Add this to your config:
```yaml
# Queue Configuration
queue:
  kind: Redis
  # Redis connection URI
  uri: {{get_env(name="REDIS_URL")}}
  # Dangerously flush all data in Redis on startup. dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_flush: false
  ```
Now execute:
```
cargo loco db create
```

See a parsing error.

**Expected Behavior**

Load the env vars from the `.env` file.

**Environment:**

**Additional Context**

/
