### ISSUE TITLE
Setting limit_payload to disabled doesn't disable payload limit

### ISSUE THREAD

**Issue by BWStearns** [loco-rs/loco#1075]
**Description**

https://github.com/loco-rs/loco/discussions/1069

**To Reproduce**

Try this setting in env/development.yaml and try uploading a 4MB file.

```
  middlewares:
    # Limit payload size for incoming requests.
    limit_payload:
      enable: false
```

**Expected Behavior**

Should upload.

**Environment:**

Dev (though presumably any)

**Additional Context**

Seems to be failing back on the default from axum.
