### ISSUE TITLE
Configuration issue involving the server binding

### ISSUE THREAD

**Issue by MatzHilven** [loco-rs/loco#1110]
**Description**
The default config contains a slight issue: 
https://github.com/loco-rs/loco/blob/481e1d0b2b345309a23ddbf1dcbde6973cef8826/starters/saas/config/development.yaml#L19
it's saying the http server will bind to `0.0.0.0` by default, instead it binds to `localhost`. This causes the application not to be exposed in containerized environments.

**Expected Behavior**

The server should bind on `0.0.0.0` by default, as the comment suggests. Or the binding configuration should be added to the configuration template so it's clearer; the comment should also be updated in this case.

It might be better to go for the first option since this can be a tricky issue to debug.

**Environment:**
It can be fixed by adding the following in the config.
```
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: 5150
  binding: 0.0.0.0
```
