### ISSUE TITLE
Missing request extension

### ISSUE THREAD

**Issue by Mettwasser** [loco-rs/loco#1126]
**Description**

Following the docs, I needed some shared state. 

So I made this struct:
```rs
#[derive(Debug, Clone)]
pub struct AppState {
    pub secret: Arc<str>,
}
```

And added the `after_routes` in Apps:
```rs
async fn after_routes(router: axum::Router, _ctx: &AppContext) -> Result<axum::Router> {
    let appstate = Arc::new(AppState {
        captcha_secret: env::var("HCAPTCHA_SECRET")
            .expect("you fucked up the config")
            .into(),
    });

    tracing::info!("ADDING EXTENSION");

    Ok(router.layer(Extension(appstate)))
}
```

I needed to make some adjustements to the registering process, where I need that shared state, so:
```rs
#[debug_handler]
async fn register(
    State(ctx): State<AppContext>,
    Extension(appstate): Extension<AppState>,
    Json(params): Json<RegisterParams>,
) -> Result<Response>
```

Results in this error when requesting:
```
Missing request extension: Extension of type `wrf::app::AppState` was not found. Perhaps you forgot to add it? See `axum::Extension`.
```
**To Reproduce**

See above, `main.rs` is the default, here's my `Cargo.toml`:
```toml
[workspace]

[package]
name = "wrf"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "wrf-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
loco-rs = { version = "0.13.2" }

[dependencies]
loco-rs = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.33.0", default-features = false, features = [
  "rt-multi-thread",
] }
async-trait = "0.1.74"
axum = "0.7.5"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
migration = { path = "migration" }
sea-orm = { version = "1.1.0", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
chrono = "0.4"
validator = { version = "0.18" }
uuid = { version = "1.6.0", features = ["v4"] }
include_dir = "0.7"
# view engine i18n
fluent-templates = { version = "0.8.0", features = ["tera"] }
unic-langid = "0.9.4"
thiserror = "2.0.9"
derive_more = { version = "1.0.0", features = ["full"] }
dotenv = "0.15.0"
reqwest = { version = "0.12.12", features = ["json"] }
# /view engine

[[bin]]
name = "wrf-cli"
path = "src/bin/main.rs"
required-features = []
[[bin]]
name = "tool"
path = "src/bin/tool.rs"
required-features = []

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
serial_test = "3.1.1"
rstest = "0.21.0"
insta = { version = "1.34.0", features = ["redactions", "yaml", "filters"] }
```

**Expected Behavior**

Expect it to run and get the state.

**Environment:**

Development, on WIndows 11.
rustc 1.83.0 (90b35a623 2024-11-26)
stable-x86_64-pc-windows-msvc

**Additional Context**

-
