### ISSUE TITLE
Upgrade broke static file serving

### ISSUE THREAD

**Issue by jtwaleson** [loco-rs/loco#1175]
**Description**

After upgrading from 0.13.2 to 0.14.0 my static file serving from frontend/dist stopped working. It now shows the fallback "Welcome to Loco!" page.

**To Reproduce**

Create an app in 0.13.2, put your frontend build in dist/frontend. Configure `config/development.yaml` like below. See that it works and your frontend is served. Then upgrade to 0.14.0 and see that you get the default loco fallback page.

```
server:
  port: 8001
  host: http://localhost:8001
  middlewares:
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/"
        path: "frontend/dist"
      fallback: "frontend/dist/index.html"

```

**Expected Behavior**

I see the normal frontend app as on 0.13.2.

**Environment:**

n/a

**Additional Context**

I had a quick look at the changes between 0.13.2 and 0.14.0 but could not see any obvious problems. Maybe the different route parsing in axum 0.8.1 has something to do with it?
