### ISSUE TITLE
Able to configure if Scheduled Task should run on start

### ISSUE THREAD

**Issue by DenuxPlays** [loco-rs/loco#1182]
## Feature Request

It would be great if the we can say that a task should start when the scheduler starts.

For example in my case I have a task that runs every 24 hours.
But I really wanted to say that the task should run on start and after that every 24 hours.

**Describe the solution you'd like**

Just add another argument to the scheduler like `run_on_start` or something like that.

**Describe alternatives you've considered**

Run the task manually or put it in the before_start hook (but this would also start the task when a worker or the server starts).

**Comment by DenuxPlays** [comment]
If this is a feature you are interested in I can open a PR for this.

**Comment by kaplanelad** [comment]
Sound good. 
You can add it to the under the yaml configuration.
For example see `run_on_start` section:
```yaml
scheduler:
  output: stdout
  jobs:
    write_content:
      shell: true
      run: "echo loco >> ./scheduler.txt"
      schedule: run every 1 second
      output: silent
      tags: ['base', 'infra']

    run_task:
      run: "foo"
      schedule: "at 10:00 am"

    list_if_users:
      run: "user_report"
      shell: true
      schedule: "* 2 * * * *"
      tags: ['base', 'users']
 run_on_start:
  - write_content
  - list_if_users
```
