### ISSUE TITLE
`cargo loco doctor` reports postgres error

### ISSUE THREAD

**Issue by ckrenslehner** [loco-rs/loco#1252]
**Description**

Hi, I want to start a loco project with `loco new`. 

I did the following: 
**1.) Start loco project** 
```
❯ : loco new
✔ ❯ App name? · loco_test
✔ ❯ What would you like to build? · Saas App with server side rendering
? ❯ Select a DB Provider ›
  Sqlite
❯ Postgres
  None
```

**2.) Start docker container**
I started the postgres container according to https://loco.rs/docs/the-app/models/ 

```
docker run -d -p 5432:5432 \
  -e POSTGRES_USER=loco \
  -e POSTGRES_DB=myapp_development \
  -e POSTGRES_PASSWORD="loco" \
  postgres:15.3-alpine
```

3.) I ran `cargo loco doctor` and got the following output

```
❯ : cargo loco doctor
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.72s
     Running `target\debug\loco_test-cli.exe doctor`
✅ SeaORM CLI is installed
❌ DB connection: fails
Connection Error: encountered unexpected or invalid data: Postgres protocol error (reading ErrorResponse): Postgres returned a non-UTF-8 string for its error message.
This is most likely due to an error that occurred during authentication and the default lc_messages locale is not binary-compatible with UTF-8. See the server logs for the error details. (sqlx_postgres::message:138)
✅ Dependencies
✅ Loco version: latest
error: process didn't exit successfully: `target\debug\loco_test-cli.exe doctor` (exit code: 1)
```

**To Reproduce**

See above

**Expected Behavior**

I guess the connection should be successful?

**Environment:**
Windows 11
Rustc 1.83
loco 0.14.0

Thanks for your help :-)

**Comment by kaplanelad** [comment]
can you share the postgres section in development.yaml?

**Comment by ckrenslehner** [comment]
Sure. That is the whole file which was created by `loco new`

``` yaml
# Loco configuration file documentation

# Application logging configuration
logger:
  # Enable or disable logging.
  enable: true
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: debug
  # Define the logging format. options: compact, pretty or json
  format: compact
  # By default the logger has filtering only logs that came from your code or logs that came from `loco` framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  # override_filter: trace

# Web server configuration
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: 5150
  # Binding for the server (which interface to bind to)
  binding: localhost
  # The UI hostname or IP address that mailers will point to.
  host: http://localhost
  # Out of the box middleware configuration. to disable middleware you can changed the `enable` field to `false` of comment the middleware block
  middlewares:
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/static"
        path: "assets/static"
      fallback: "assets/static/404.html"

# Initializers Configuration
# initializers:
#  oauth2:
#    authorization_code: # Authorization code grant type
#      - client_identifier: google # Identifier for the OAuth2 provider. Replace 'google' with your provider's name if different, must be unique within the oauth2 config.
#        ... other fields

# Database Configuration
database:
  # Database connection URI
  uri: {{ get_env(name="DATABASE_URL", default="sqlite://test_loco_development.sqlite?mode=rwc") }}
  # When enabled, the sql query will be logged.
  enable_logging: false
  # Set the timeout duration when acquiring a connection.
  connect_timeout: {{ get_env(name="DB_CONNECT_TIMEOUT", default="500") }}
  # Set the idle duration before closing a connection.
  idle_timeout: {{ get_env(name="DB_IDLE_TIMEOUT", default="500") }}
  # Minimum number of connections for a pool.
  min_connections: {{ get_env(name="DB_MIN_CONNECTIONS", default="1") }}
  # Maximum number of connections for a pool.
  max_connections: {{ get_env(name="DB_MAX_CONNECTIONS", default="1") }}
  # Run migration up when application loaded
  auto_migrate: true
  # Truncate database when application loaded. This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_truncate: false
  # Recreating schema when application loaded.  This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_recreate: false
```
