### ISSUE TITLE
Dedicated worker for job type

### ISSUE THREAD

**Issue by kaplanelad** [loco-rs/loco#1327]
Discussion: # #1308

**Comment by jtwaleson** [comment]
Started here: https://github.com/jtwaleson/loco/commit/99a939f0969d9ebb95ed3b8378b1c081608c1305 

Let me know what you think.

I tried to get this in the CLI but struggled a bit, so went for the simplest option, which is a different config file per worker type.

In the main one I just do:

```yaml
num_workers: 3
exclude_job_types:
- CPUIntensiveTask
```

This will do network requests, sync jobs etc.

And in the other:

```yaml
num_workers: 1
include_job_types:
- CPUIntensiveTask
```
