### ISSUE TITLE
Extract valadation to a workspace package

### ISSUE THREAD

**Issue by NexVeridian** [loco-rs/loco#1339]
Sightly related issues: #1215 #1338

When using a rust web framework, using the same validator for the client and server is common, so I think the validator coder should be moved to a workspace package

I think having all validator in one place would also look nicer 

### notes:
- /src has wasm incompatible code, so /src can't be used in the web framework code
- meaning that this is also wasm incompatible, I think:
  ```rust
  impl Validatable for ActiveModel {
    fn validator(&self) -> Box<dyn Validate> {
        Box::new(Validator {
            name: self.name.as_ref().to_owned(),
            email: self.email.as_ref().to_owned(),
            password: self.password.as_ref().to_owned(),
        })
    }
  }
  ```

## This is what I have in my current code: 
```toml
# /validation/cargo.toml
[package]
name = "validation"
version = "0.1.0"
edition = "2024"
publish = false
rust-version = "1.87"

[lints]
workspace = true

[lib]
name = "validation"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
validator = { version = "0.20", features = ["derive"] }
```

```rust
// /validation/src/lib.rs
use serde::{Deserialize, Serialize};
pub use validator::{self, Validate};

#[derive(Default, Debug, Validate, Deserialize)]
pub struct Validator {
    #[validate(length(min = 5, message = "Name must be at least 5 characters long."))]
    pub name: String,
    #[validate(email(message = "Invalid email address."))]
    pub email: String,
    #[validate(length(min = 25, message = "Password must be at least 25 characters long."))]
    pub password: String,
}

#[derive(Default, Debug, Validate, Deserialize, Serialize)]
pub struct LoginParams {
    #[validate(email(message = "Invalid email address."))]
    pub email: String,
    #[validate(length(min = 25, message = "Password must be at least 25 characters long."))]
    pub password: String,
}

#[derive(Default, Debug, Validate, Deserialize, Serialize)]
pub struct RegisterParams {
    #[validate(length(min = 5, message = "Name must be at least 5 characters long."))]
    pub name: String,
    #[validate(email(message = "Invalid email address."))]
    pub email: String,
    #[validate(length(min = 25, message = "Password must be at least 25 characters long."))]
    pub password: String,
}

#[derive(Default, Debug, Validate, Deserialize, Serialize)]
pub struct ForgotParams {
    #[validate(email(message = "Invalid email address."))]
    pub email: String,
}

#[derive(Default, Debug, Validate, Deserialize, Serialize)]
pub struct ResetParams {
    pub token: String,
    #[validate(length(min = 25, message = "Password must be at least 25 characters long."))]
    pub password: String,
}

#[derive(Default, Debug, Validate, Deserialize, Serialize)]
pub struct MagicLinkParams {
    #[validate(email(message = "Invalid email address."))]
    pub email: String,
}
```
