### ISSUE TITLE
0.15 unable start scheduler: Error: Scheduler(Empty)

### ISSUE THREAD

**Issue by Paulswith** [loco-rs/loco#1378]
**Description**

I using 0.15 create a new project, unable run any relate to scheduler commands, always raise `Error: Scheduler(Empty)`

**To Reproduce**

`loco new`
✔ ❯ App name? · scheduler-bug
✔ ❯ What would you like to build? · Rest API (with DB and user auth)
✔ ❯ Select a DB Provider · None
✔ ❯ Select your background worker type · Async (in-process tokio async tasks)

`cd scheduler-bug`
`cargo loco generate scheduler`
`cargo loco scheduler --list`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/scheduler_bug-cli scheduler --list`
2025-04-19T16:25:14.456866Z  WARN app: loco_rs::boot: pretty backtraces are enabled (this is great for development but has a runtime cost for production. disable with `logger.pretty_backtrace` in your config yaml) environment=development
Error: Scheduler(Empty)

**Expected Behavior**

**Environment:**
Cargo.toml
```toml
[workspace]

[package]
name = "scheduler-bug"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "scheduler_bug-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
loco-rs = { version = "0.15", default-features = false }

[dependencies]
loco-rs = { workspace = true , features = ["cli", "bg_redis"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
tokio = { version = "1.33.0", default-features = false, features = [
  "rt-multi-thread",
] }
async-trait = { version = "0.1.74" }
axum = { version = "0.8.1" }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
regex = { version = "1.11.1" }

[[bin]]
name = "scheduler_bug-cli"
path = "src/bin/main.rs"
required-features = []

[dev-dependencies]
loco-rs = { workspace = true, features = ["testing"] }
serial_test = { version = "3.1.1" }
rstest = { version = "0.21.0" }
insta = { version = "1.34.0", features = ["redactions", "yaml", "filters"] }
```

 config/scheduler.yaml
```yaml
output: stdout
jobs:
  write_content:
      shell: true
      run: "echo loco >> ./scheduler.txt"
      schedule: run every 1 second
      # schedule: "* * * * * * *"
      output: silent
      tags: ['base', 'infra']

  # run_task:
  #     run: "foo"
  #     schedule: "at 10:00 am"
```
**Additional Context**
