### ISSUE TITLE
Asynchronous caching from Controller to Scheduler

### ISSUE THREAD

**Issue by anhnmt** [loco-rs/loco#1422]
**Description**

I launch the app with the --all flag: app + scheduler + worker.

I have inserted a key into the cache inmem in the app.

But when I get it from Scheduler + Task, there is no value

**To Reproduce**

```
scheduler:
  output: stdout
  jobs:
    video_task:
      run: "video_task"
      schedule: "0 */5 * * * *" # every 5 minutes
```

```rust
ctx.cache
            .insert_with_expiry(
                &format!("upload:{}", name),
                "body".
                Duration::from_secs(5 * 60),
            )
            .await?;
```

Task run using Scheduler

```rust
async fn run(&self, ctx: &AppContext, _vars: &task::Vars) -> Result<()> {
    if ctx.cache.contains_key(&format!("upload:{}", name)).await? {
        info!("Video name: {}", name);
        continue;
    }
}
```

**Expected Behavior**

When I insert a key from the Controller side, the Scheduler + Task also receives it.

**Environment:**
Loco v0.15.0
