### ISSUE TITLE
 Redis connection: failed after upgrade to 0.2.5 from 0.2.4

### ISSUE THREAD

**Issue by tjyang** [loco-rs/loco#229]
**Description**

Vaguely remember  **cargo loco doctor** reported all DB connections were fine in loco/examples/demo directory

**To Reproduce**

- create a container with loco_app
```
docker run -d -p 5432:5432 -e POSTGRES_USER=loco -e POSTGRES_DB=loco_app -e POSTGRES_PASSWORD="loco" postgres:15.3-alpine
```
- now run the check
```
[me@rocky9t01a demo]$ cargo loco doctor
    Finished dev [unoptimized + debuginfo] target(s) in 0.32s
     Running `target/debug/blo-cli doctor`
✅ SeaORM CLI is installed
✅ DB connection: success
❌ Redis connection: failed
Timed out in bb8
[me@rocky9t01a demo]$ pwd
/home/me/github/learnrust/loco/examples/demo
[me@rocky9t01a demo]$
```

**Expected Behavior**

redis connection passed

**Environment:**

```
[me@rocky9t01a demo]$ loco -V;cat /etc/redhat-release
loco-cli 0.2.5
Rocky Linux release 9.3 (Blue Onyx)
[me@rocky9t01a demo]$

```
**Additional Context**

NA

**Comment by kaplanelad** [comment]
Can you share with us the `docker ps` outputs and the development yaml configuration?  make sure you not have sensitive date there

**Comment by tjyang** [comment]
- pg container
```
docker run -d -p 5432:5432 -e POSTGRES_USER=loco -e POSTGRES_DB=loco_app -e POSTGRES_PASSWORD="loco" postgres:15.3-alpine

[me@rocky9t01a demo]$ docker ps -a |egrep 'CONTAIN|alpine'
CONTAINER ID   IMAGE                       COMMAND                  CREATED              STATUS                PORTS                                         NAMES
ffc1052c85b9   postgres:15.3-alpine        "docker-entrypoint.s…"   About a minute ago   Up About a minute     0.0.0.0:5432->5432/tcp, :::5432->5432/tcp     tender_borg
[me@rocky9t01a demo]$
[me@rocky9t01a demo]$ cargo loco doctor
    Finished dev [unoptimized + debuginfo] target(s) in 0.29s
     Running `target/debug/blo-cli doctor`
✅ SeaORM CLI is installed
✅ DB connection: success
❌ Redis connection: failed
Timed out in bb8
[me@rocky9t01a demo]$
```
- config/developement.yml
```
[me@rocky9t01a demo]$ cat config/development.yaml
# Loco configuration file documentation

settings:
  allow_list:
    - google.com
    - apple.com

# Application logging configuration
logger:
  # Enable or disable logging.
  enable: true
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: debug
  # Define the logging format. options: compact, pretty or Json
  format: compact
  # By default the logger has filtering only logs that came from your code or logs that came from `loco` framework. to see all third party libraries
  # Uncomment the line below to override to see all third party libraries you can enable this config and override the logger filters.
  # override_filter: trace

# Web server configuration
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: {{ get_env(name="NODE_PORT", default=3000) }}
  # The UI hostname or IP address that mailers will point to.
  host: http://localhost
  # Out of the box middleware configuration. to disable middleware you can changed the `enable` field to `false` of comment the middleware block
  middlewares:
    # Allows to limit the payload size request. payload that bigger than this file will blocked the request.
    limit_payload:
      # Enable/Disable the middleware.
      enable: true
      # the limit size. can be b,kb,kib,mb,mib,gb,gib
      body_limit: 5mb
    # Generating a unique request ID and enhancing logging with additional information such as the start and completion of request processing, latency, status code, and other request details.
    logger:
      # Enable/Disable the middleware.
      enable: true
    # when your code is panicked, the request still returns 500 status code.
    catch_panic:
      # Enable/Disable the middleware.
      enable: true
    # Timeout for incoming requests middleware. requests that take more time from the configuration will cute and 408 status code will returned.
    timeout_request:
      # Enable/Disable the middleware.
      enable: true
      # Duration time in milliseconds.
      timeout: 5000
    cors:
      enable: true
      # Set the value of the [`Access-Control-Allow-Origin`][mdn] header
      # allow_origins:
      #   - https://loco.rs
      # Set the value of the [`Access-Control-Allow-Headers`][mdn] header
      # allow_headers:
      # - Content-Type
      # Set the value of the [`Access-Control-Allow-Methods`][mdn] header
      # allow_methods:
      #   - POST
      # Set the value of the [`Access-Control-Max-Age`][mdn] header in seconds
      # max_age: 3600

# Worker Configuration
workers:
  # specifies the worker mode. Options:
  #   - BackgroundQueue - Workers operate asynchronously in the background, processing queued.
  #   - ForegroundBlocking - Workers operate in the foreground and block until tasks are completed.
  #   - BackgroundAsync - Workers operate asynchronously in the background, processing tasks with async capabilities.
  mode: BackgroundQueue

# Mailer Configuration.
mailer:
  # SMTP mailer configuration.
  smtp:
    # Enable/Disable smtp mailer.
    enable: true
    # SMTP server host. e.x localhost, smtp.gmail.com
    host: localhost
    # SMTP server port
    port: 1025
    # Use secure connection (SSL/TLS).
    secure: false
    # auth:
    #   user:
    #   password:

# Database Configuration
database:
  # Database connection URI
  uri: {{ get_env(name="DATABASE_URL", default="postgres://loco:loco@localhost:5432/loco_app") }}
  # When enabled, the sql query will be logged.
  enable_logging: false
  # Set the timeout duration when acquiring a connection.
  connect_timeout: 500
  # Set the idle duration before closing a connection.
  idle_timeout: 500
  # Minimum number of connections for a pool.
  min_connections: 1
  # Maximum number of connections for a pool.
  max_connections: 1
  # Run migration up when application loaded
  auto_migrate: true
  # Truncate database when application loaded. This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_truncate: false
  # Recreating schema when application loaded.  This is a dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_recreate: false

# Redis Configuration
redis:
  # Redis connection URI
  uri: {{ get_env(name="REDIS_URL", default="redis://127.0.0.1") }}
  # Dangerously flush all data in Redis on startup. dangerous operation, make sure that you using this flag only on dev environments or test mode
  dangerously_flush: false

# Authentication Configuration
auth:
  # JWT authentication
  jwt:
    # Secret key for token generation and verification
    secret: PqRwLF2rhHe8J22oBeHy
    # Token expiration time in seconds
    expiration: 604800 # 7 days
[me@rocky9t01a demo]$ pwd
/home/me/github/learnrust/loco/examples/demo
[me@rocky9t01a demo]$

```
