### ISSUE TITLE
0.0.0.0 not working to expose ports

### ISSUE THREAD

**Issue by BWStearns** [loco-rs/loco#704]
**Description**

I need to expose a webapp to the local network. The non-local device cannot see the webservice. I started a new project using 0.7.0 and modified the `development.yaml` file like below.

```
# development.yaml
# Web server configuration
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: 5150
  # The UI hostname or IP address that mailers will point to.
  host: http://0.0.0.0
```
(I also tried my machine's hostname instead of `0.0.0.0`).

My second device cannot access the server via the hostname of the server or the local ip address.

The start logging makes me think it might be ignoring the `0.0.0.0` host input in favor of just localhost?

```
                https://loco.rs

environment: development
     logger: debug
compilation: debug
      modes: server

listening on localhost:5150
```
