### ISSUE TITLE
Default configuration

### ISSUE THREAD

**Issue by kaplanelad** [loco-rs/loco#9]
In our library, we provide support for any environment specified by the user, requiring only a configuration file with a matching environment name. In this configuration file, the user must include all the expected settings. For example, in a YAML configuration file:
```yaml
logger:
  enable: true
  level: info
  format: compact
  # filters:
  #   - sea_orm_migration=error
server:
  port: 3000
  middlewares:
    limit_payload:
      enable: true
...
```

To simplify configuration and not breaking the app when user upgrade our crate, we propose allowing users to specify only the mandatory settings, with the option to automatically inherit the remaining configurations from our defaults. Users can then override any specific settings as needed. For instance:
```yaml
database:
  uri: postgres://root:12341234@localhost:5432/rr_app
redis:
  uri: redis://127.0.0.1/
```
